-- CREATE DATABASE SoftUni

USE SoftUni

CREATE TABLE Towns(
	Id INT IDENTITY NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	CONSTRAINT PK_Towns PRIMARY KEY(Id)
)

CREATE TABLE Addresses(
	Id INT IDENTITY NOT NULL,
	AddressText NVARCHAR(100) NOT NULL,
	TownId INT NOT NULL,
	CONSTRAINT PK_Addresses PRIMARY KEY(Id),
	CONSTRAINT FK_Addresses_TownId FOREIGN KEY (TownId) REFERENCES Towns (Id)
)

CREATE TABLE Departments(
	Id INT IDENTITY NOT NULL,
	Name VARCHAR(100) NOT NULL,
	CONSTRAINT PK_Departments PRIMARY KEY(Id)
)

CREATE TABLE Employees (
	Id INT IDENTITY,
	FirstName NVARCHAR(100) NOT NULL,
	MiddleName NVARCHAR(100),
	LastName NVARCHAR(100) NOT NULL,
	JobTitle NVARCHAR(100) NOT NULL, 
	DepartmentId INT NOT NULL, 
	HireDate DATE NOT NULL, 
	Salary MONEY NOT NULL, 
	AddressId INT,
	CONSTRAINT PK_Employees PRIMARY KEY (Id),
	CONSTRAINT FK_Employees_Departments FOREIGN KEY (DepartmentId) REFERENCES Departments (Id),
	CONSTRAINT FK_Employees_Addresses FOREIGN KEY (AddressId) REFERENCES Addresses (Id),
	CONSTRAINT CK_Employees_Salary CHECK (Salary >= 0)
)